In [1]:
In [1]: %load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [1]:
##hacer analisis exploratorio, a los 3 archivos
##subirlo a github,
##hacer un git commit, en el visual.
companies = catalog.load("companies")
companies.head()

[03/19/26 15:27:57] INFO     Loading data from companies (CSVDataset)...                       ]8;id=629929;file://C:\Users\Pavillion\AppData\Local\Programs\Python\Python313\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=693998;file://C:\Users\Pavillion\AppData\Local\Programs\Python\Python313\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,f
1,46728,100%,NaN,1.0,f
2,34618,38%,Isle of Man,1.0,f
3,28619,100%,Bosnia and Herzegovina,1.0,f
4,8240,NaN,Chile,1.0,t

In [2]:
shuttles=catalog.load("shuttles")
shuttles.head()

[03/19/26 15:29:33] INFO     Loading data from shuttles (ExcelDataset)...                      ]8;id=411371;file://C:\Users\Pavillion\AppData\Local\Programs\Python\Python313\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=699635;file://C:\Users\Pavillion\AppData\Local\Programs\Python\Python313\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,f,f,"$3,405.0",14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,806.0",47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,f,f,"$1,676.0",26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,f,f,"$4,718.0",26648

In [3]:
reviews=catalog.load("reviews")
reviews.head()

[03/19/26 15:30:17] INFO     Loading data from reviews (CSVDataset)...                         ]8;id=60968;file://C:\Users\Pavillion\AppData\Local\Programs\Python\Python313\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=499031;file://C:\Users\Pavillion\AppData\Local\Programs\Python\Python313\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22
4,5067,97.0,10.0,9.0,10.0,10.0,9.0,10.0,22,0.29